### ISSUE TITLE
RSpec Expectation syntax 

### ISSUE THREAD

**Issue by hicksca** [RubyoffRails/Episode1-Summer2012#41]
While trying to complete the exercise I ran into a deprecation warning:

```
Using `should` from rspec-expectations' old `:should` syntax without explicitly 
enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly 
enable `:should` with`config.expect_with(:rspec) { |c| c.syntax = :should }` instead.
```

This is not a big deal but I then tried went down the road of trying to write the test using the `expect` syntax, and I'm having trouble with accessing instance variables.
For example:

``` Ruby
# Card Class
0 class Card
1
2     attr_reader :suit, :value
3     def initialize(suit, value)
4         @suit = suit
5         @value = value
6     end
7
8 end
```

``` Ruby
# Test case
0 describe Card do
1
2     it "expect to accept suit and value when building" do
3         card = Card.new(:clubs, 10)
4         expect(card).to eq(:clubs)  #<-- I'm unable to use card.suit or card.new.suit(:site, :value)   
5         #expect(card).to eq(10)
6     end
7 end
```

How would I write this test using the `expect` syntax?

error message from Rspec:

```
F

Failures:

  1) Card expect to accept suit and value when building
     Failure/Error: expect(card.value).to eq(10)
     NoMethodError:
       undefined method `value' for #<Card:0x007fa902915c00 @suit=:clubs, @value=10>
     # ./blackjack.rb:18:in `block (2 levels) in <top (required)>'

Finished in 0.00137 seconds (files took 0.16479 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./blackjack.rb:15 # Card expect to accept suit and value when building
```

```
Failures:

  1) Card expect to accept suit and value when building
     Failure/Error: expect(card).to eq(:clubs)

       expected: :clubs
            got: #<Card:0x007fc89a8363e0 @suit=:clubs, @value=10>

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -:clubs
       +#<Card:0x007fc89a8363e0 @suit=:clubs, @value=10>
     # ./blackjack.rb:17:in `block (2 levels) in <top (required)>'

Finished in 0.02727 seconds (files took 0.15817 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./blackjack.rb:15 # Card expect to accept suit and value when building
```

**Comment by jwo** [comment]
@hicksca  here you go:

``` ruby
expect(card.suit).to eq(:clubs)
```

**Comment by hicksca** [comment]
I'm not sure why that didn't work when I was trying it last night but thank you.
